# Generated by Django 2.1 on 2018-08-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_facture', models.CharField(max_length=20)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant', models.IntegerField()),
                ('depense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_factures.Depense')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('montant_total', models.IntegerField()),
                ('montant_utilisé', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_factures.Facture')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='paragraphe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_des_factures.Paragraphe'),
        ),
    ]
